#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --time=00:10:00
#SBATCH --job-name=AlN_scf

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

srun -n 4 pw.x -nk 2 -in AlN_relax.in > ../output/relax/AlN_relax_kpoint16.out
