#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --time=00:20:00
#SBATCH --job-name=TiN_scf_cutoff40_scf.out

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

srun -n 4 pw.x -nk 2 -in TiN_scf.in > ../output/TiN_scf_cutoff40.out
