#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=32
#SBATCH --time=00:20:00
#SBATCH --job-name=AlN_scf_nodetest

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

srun pw.x -nk 2 -in AlN_scf.in > ../output/nodes/AlN_relaxednodes1.out
