#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=4
#SBATCH --time=03:10:00
#SBATCH --job-name=TiAlN-scf

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

srun -n 4 pw.x -nk 2 -in TiAlN_scf2.in > TiAlN_scf2.out
