#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=32
#SBATCH --time=01:00:00
#SBATCH --job-name=TiN_bands

set -e

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

mkdir -p ../output/bands

mpprun pw.x -nk 4 -in TiN_bands.in > ../output/bands/TiN_bands.out
srun -n 1 bands.x < TiN_bands_pp.in > ../output/bands/TiN_bands_pp.out
