#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --time=00:20:00
#SBATCH --job-name=AlN_scf

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

srun -n 12 pw.x -nk 2 -in AlN_scf.in > ../output/band/AlN_scfinfile.out
