#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --time=00:10:00
#SBATCH --job-name=AlN_scf

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

srun -n 16 pw.x -nk 4 -in AlN_band.in > ../output/band/AlN_band.out
