#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=4
#SBATCH --time=00:10:00
#SBATCH --job-name=TiN_relax

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

mpprun pw.x -nk 2 -in TiN_vc_relax.in > TiN_vc_relax.out
