#!/bin/bash
#SBATCH -A liu-compute-2026-1
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --time=00:10:00
#SBATCH --job-name=AlN_bands

module load QuantumESPRESSO/7.1
export OMP_NUM_THREADS=1

srun bands.x < band.in > ../output/band/AlN_bands_post.out
